config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :ramen_shops, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ramen_shop.rb
class RamenShop < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :ramen_shop
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/ramen_shops_controller.rb
class RamenShopsController < ApplicationController
  def index
    @ramen_shops = RamenShop.all
  end

  def show
    @ramen_shop = RamenShop.find(params[:id])
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ramen_shops_helper.rb
module RamenShopsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/top.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
          <p class="is-size-1 has-text-weight-bold has-text-centered">レビューを自由に</p>
          <br>
          <div class="columns is-centered">
            <div class="column is-3">
              <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
              <br>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-fullwidth" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</section

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RamenReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/9132c54d20.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-3" style="font-family: cursive; color: black;">ramen review</strong>
          <% end %>
        </p>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to root_path, class: "navbar-item" do %>
            ラーメン店一覧
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ <%= current_user.username %> さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/ramen_shops/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @ramen_shops.each do |ramen_shop| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= ramen_shop.name %>
              </p>
            </header>
            <div class="card-content">
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: %">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
            </footer>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/ramen_shops/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @ramen_shop.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: %">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                点（<%= @ramen_shop.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, ramen_shop: @ramen_shop %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<div class="raiting-box mt-3">
  <%= form_with model: review, url: ramen_shop_reviews_path(ramen_shop), local: true do |f| %>
    <div class="main-raiting">
      <div class="raitings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :ramen_shop_id, value: ramen_shop.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", ramen_shop_reviews_path(ramen_shop), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>